#!/bin/sh

set +e
rm -rf tmp/redis
mkdir tmp
set -e

version=${MARCONI_BRANCH:-master}

pushd tmp

git clone https://git.openstack.org/openstack/marconi -b $version

cd marconi
$OPENSHIFT_DATA_DIR/bin/pip install .

popd
rm -rf tmp/redis
