#!/bin/sh

set +e
rm -rf tmp/redis
rm -rf venv
mkdir tmp
set -e

version=${MARCONI_BRANCH:-master}
virtualenv venv
source venv/bin/activate

pushd tmp

git clone https://git.openstack.org/openstack/marconi -b $version

cd marconi
pip install .

popd
rm -rf tmp/marconi
