#!/bin/sh

set +e
rm -rf tmp/redis
mkdir tmp
set -e

version=${MARCONI_BRANCH:-master}

pushd tmp

git clone https://git.openstack.org/openstack/marconi -b $version

cd marconi
python setup.py install

popd
rm -rf tmp/redis
